#!/bin/sh
PATH=./node_modules/.bin:$PATH

function debug {
    echo "Stopped in REPL. Press ^D to resume, or ^C to abort."
    local line
    while read -r -p "> " line; do
        eval "$line"
    done
    echo
}

function apply { ## Apply updates to System or User accounts < system | user username >
    if [ $# -lt 1 ]; then echo 1>&2 "Usage: $0 $FUNCNAME < system | user username >";exit 3;fi

    if [ $1 = "system" ]; then
        echo "Applying system changes..."
        sudo nixos-rebuild switch -I nixos-config=/home/.dotfiles/system/configuration.nix
    fi
    
    if [ $1 = "user" ]; then
        echo "Applying user level changes for user $2..."
	sudo runuser -l $2 sh -c "cd /home/.dotfiles/users/$2 && home-manager switch -f home.nix"
    fi
}

function hm { ## Add, install or update home-manager for user < add username | install username | update username >
    if [ $# -ne 2 ]; then echo 1>&2 "Usage: $0 $FUNCNAME < add username | install username | update username >";exit 3;fi

    if [ $1 = "add" ]; then
        echo "Adding home-manager channel for user $2"
        sudo runuser -l $2 sh -c "nix-channel --add https://github.com/nix-community/home-manager/archive/release-21.05.tar.gz home-manager && nix-channel --update"
	echo "Please logout and back in and then run $0 $FUNCNAME install $2"
    fi
    
    if [ $1 = "install" ]; then
        echo "Installing home-manager channel for user $2"
        sudo runuser -l $2 sh -c "nix-shell '<home-manager>' -A install"
    fi
}

function default {
    help
}

function help { ## Display usage for this application
    echo "$0 <task> <args>"
    grep -E '^function [a-zA-Z_-]+ {.*?## .*$$' $0 | sed -e 's/function //' | sort | awk 'BEGIN {FS = "{.*?## "}; {printf "\033[93m%-30s\033[92m %s\033[0m\n", $1, $2}'
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
