#!/bin/sh
PATH=./node_modules/.bin:$PATH

function debug {
    echo "Stopped in REPL. Press ^D to resume, or ^C to abort."
    local line
    while read -r -p "> " line; do
        eval "$line"
    done
    echo
}

function apply { ## Apply configuration changes for System or User accounts < system | user username >
    if [ $# -lt 1 ]; then echo 1>&2 "Usage: $0 $FUNCNAME < system | user username >";exit 3;fi

    if [ $1 = "system" ]; then
        echo "Applying system changes..."
        sudo nixos-rebuild switch -I nixos-config=/home/.dotfiles/system/configuration.nix
    fi

    if [ $1 = "user" ]; then
        if [ $# -ne 2 ];then echo 1>&2 "Username is required for $0 $FUNCNAME $1";exit 3;fi

        echo "Applying user level changes for user $2..."
	sudo runuser -l $2 sh -c "cd /home/.dotfiles/users/$2 && home-manager switch -f home.nix"
    fi
}

function update { ## Apply updates to System or User accounts < system | user username >
    if [ $# -lt 1 ]; then echo 1>&2 "Usage: $0 $FUNCNAME < system | user username >";exit 3;fi

    if [ $1 = "system" ]; then
        echo "Applying system updates..."
        sudo nix-channel --update
    fi

    if [ $1 = "user" ]; then
        if [ $# -ne 2 ];then echo 1>&2 "Username is required for $0 $FUNCNAME $1";exit 3;fi

        echo "Applying user level updates for user $2..."
        sudo runuser -l $2 sh -c "nix-channel --update"
    fi
}


function hm { ## Add, install or update home-manager for user < add username | install username | update username >
    if [ $# -ne 2 ]; then echo 1>&2 "Usage: $0 $FUNCNAME < add username | install username | update username >";exit 3;fi

    if [ $1 = "add" ]; then
        echo "Adding home-manager channel for user $2"
        sudo runuser -l $2 sh -c "nix-channel --add https://github.com/nix-community/home-manager/archive/release-21.05.tar.gz home-manager && nix-channel --update"
	echo "Please logout and back in and then run $0 $FUNCNAME install $2"
    fi

    if [ $1 = "install" ]; then
        echo "Installing home-manager channel for user $2"
        sudo runuser -l $2 sh -c "nix-shell '<home-manager>' -A install"
    fi
}

function edit { ## Edit the scripts or configurations in the nix-manager folder < nm | config | hardware | user username >
    if [ $# -lt 1 ]; then echo 1>&2 "Usage: $0 $FUNCNAME < nm | config | hardware | user username >";exit 3;fi

    if [ $1 = "nm" ]; then
        sudo nix-shell -p vim git --run "vim /home/.dotfiles/nm"
    fi

    if [ $1 = "config" ]; then
        sudo nix-shell -p vim git --run "vim /home/.dotfiles/system/configuration.nix"
    fi

    if [ $1 = "hardware" ]; then
        sudo nix-shell -p vim git --run "vim /home/.dotfiles/system/hardware-configuration.nix"
    fi

    if [ $1 = "user" ]; then
        if [ $# -ne 2 ];then echo 1>&2 "Username is required for $0 $FUNCNAME $1";exit 3;fi

        echo "Openeing up editor in user configuration directory for user $2..."
        code /home/.dotfiles/users/$2
    fi
}

function cleanup { ## Run garbage collection for the system or specific user < nm | config | hardware | user username >
    if [ $# -lt 1 ]; then echo 1>&2 "Usage: $0 $FUNCNAME < nm | config | hardware | user username >";exit 3;fi

    if [ $1 = "system" ]; then
        sudo rm /nix/var/nix/gcroots/auto/*
        sudo nix-collect-garbage -d
        sudo nix-store --optimise
    fi

    # if [ $1 = "user" ]; then
    #     if [ $# -ne 2 ];then echo 1>&2 "Username is required for $0 $FUNCNAME $1";exit 3;fi

    #     echo "Openeing up editor in user configuration directory for user $2..."
    #     code /home/.dotfiles/users/$2
    # fi
}

function default {
    help
}

function help { ## Display usage for this application
    echo "$0 <task> <args>"
    grep -E '^function [a-zA-Z_-]+ {.*?## .*$$' $0 | sed -e 's/function //' | sort | awk 'BEGIN {FS = "{.*?## "}; {printf "\033[93m%-30s\033[92m %s\033[0m\n", $1, $2}'
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
