# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4e40d5c0-265f-4e54-8ac6-61bb8db59927";
      fsType = "btrfs";
      options = [ "subvol=nixos" "compress=zstd" "noatime" "nodiratime" "discard" ];
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/55981d20-1242-4142-b4f8-ed6cb471eee4";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5042-2986";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/dc73902e-16b4-47a6-9073-b5318c96045d"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
